### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by jenthornbloom** [kthornbloom/Cottontail-2#7]
Could you add icons for the following?
- Yelp
- Phone
- Mobile phone
- Email

**Comment by kthornbloom** [comment]
Updated. If there is a site that needs these (or other icons) added:

- Look in the /icons directory here. Copy the icon you need.
- Paste it into the /icons directory in the project you are working on
- Run grunt. It will now be available using:

`<svg class="icon"><use xlink:href="images/sprite.svg#icon-PUTICONNAMEHERE"></use></svg>`

**Comment by kthornbloom** [comment]
By the way- I updated the cheatsheet.html file in this demo to include all available icons.
